### PR TITLE
Retry table creation if it failed (issue 268)

### PR DESCRIPTION
**Pull request by bk-jb**
#268

### CODE REVIEW

**Comment by hollandThomas** [comment]
@voxpelli Hey, is it possible to merge this? Our staging env just crashed because of this and we'd like to avoid forking this repo.

Thank you!

**Comment by voxpelli** [comment]
> @voxpelli Hey, is it possible to merge this? Our staging env just crashed because of this and we'd like to avoid forking this repo.

I do have some time today I think, I'll try looking into it in an hour or two

**Comment by voxpelli** [comment]
I have proposed an alternative fix: https://github.com/voxpelli/node-connect-pg-simple/pull/285

@bk-jb @hollandThomas Comments welcome on that approach

**Comment by hollandThomas** [comment]
That works for us 👍

**Comment by voxpelli** [comment]
Closing in favor of merged #285, thanks for the PR though and sorry for the lack of attention from me!

**Pull request closed without merging**
