### PR TITLE
Use a single UPSERT like query to set a session

### PR DESCRIPTION
**Pull request by hmalphettes**
Hi!

This enhancement replaces the 2 SQL queries `INSERT+UPDATE` by a single `UPSERT` like query.

It relies on `INSERT ... ON CONFLICT`, which requires postgres-9.5 (Jan 2016) or more recent: https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29

Please let me know if you are interested by this feature.
I can contribute some time to detect older versions of postgres and fallback to an `INSERT+UPDATE` in that case.

### CODE REVIEW

**Comment by voxpelli** [comment]
It sounds like a good addition to the next major version.

One thing I would like for this PR though is to stick to just this change and not do any unrelated changes, like using new env variables or changing unrelated dependency ranges.

**Comment by hmalphettes** [comment]
Thanks @voxpelli 
I found out while working on #50 that I should fix the tests first of all.
I built this one on the top of #50 as I was in a hurry to use it for my own internal project and I wanted to make sure all the tests were green.

I can make a separate PR, but I would find it easier to start from a state of the code where the travis build is green. My apologies for stating the obvious.
Here is what I needed to do: https://github.com/voxpelli/node-connect-pg-simple/pull/50#issuecomment-331034385

**Comment by voxpelli** [comment]
@hmalphettes yeah, I looked at your other PR after this one and then realized this includes the changes of that one.

If you could rebase your code and submit a fix for the tests as a separate PR and then update your two PR:s to rely on that PR then I could merge the fix for the tests right away.

Apart from the test fixes and the fixes in the PR:s – there are still some other changes here – like an additional environment variable. Would love to have them as separate PR:s as well, because I'm not as sure about eg. that one.

**Comment by voxpelli** [comment]
Closed in favor of #140

**Pull request closed without merging**
