### PR TITLE
Support Express <4 style sessions

### PR DESCRIPTION
**Pull request by evansolomon**
Not sure if you're interested in this but I needed it for a project using Sails, which is still on Express 3. Shouldn't change any existing behavior, just supports old style configurations.

### CODE REVIEW

**Comment by voxpelli** [comment]
Doesn't the suggested Express 3 usage that's in the README work for Sails-based apps? I had this request before, #21, and I don't really see the need for it – especially as Express 3 should have stopped receiving updates by now according to http://expressjs.com/3x/api.html:

> Express 3.x support is ending soon
>
> This series will continue to receive only security updates and bug fixes until July 2015.

Does Sails do something special on top of Express that makes the workaround suggested in the README not doable with Sails? Also, out of curiosity, does Sails have any plans on moving to Express 4? Considering that Express 3 will become, or already is, unsupported it feels like such a move should be done by that project as soon as possible.

**Comment by evansolomon** [comment]
> Does Sails do something special on top of Express that makes the workaround suggested in the README not doable with Sails?

Yea. Sails uses config files for a bunch of things, including sessions, so you don't directly load middleware and can't change the arguments.

As for Sails moving to Express 4, I know there have been discussions about it in the project's github issues but I don't know what the plan is.

Since you've already had an issue on the same topic, I'll close this.

**Comment by voxpelli** [comment]
Merged the previous PR now and will go ahead an release a new patch version. As Sails uses config files it seems like the ordinary Express 3 workaround doesn't work there so adding support for it does make sense to me.

Sorry for the delay.

**Comment by evansolomon** [comment]
👍

**Pull request closed without merging**
